import { Inter } from "next/font/google";
import "./globals.css";
import  '../styles/main.scss';


import Nav from "../components/navbar/Nav";
import DotRing from '../components/cursor/DotRing'; 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={inter.className}>
        <Nav />
        {children}
        <DotRing />
      </body>
    </html>
  );
}
